title: ChiZhang's Blog
author: chizhang
email: zhangchilyg@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog

# social links
github_username:  raven99 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
